version: '3.9'

services:
  resume-service:
    build:
      context: .
      dockerfile: services/resume-service/Dockerfile
    restart: always
    networks:
      - app-network
    ports:
      - "${RESUME_PORT}:${RESUME_PORT}"
    depends_on:
      - mysql
    command: npm run start:dev
    volumes:
      - './services/resume-service/src/:/app/src/'
      - './node_modules/:/app/node_modules/'
  
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network

volumes:
  my-db:

networks:
  app-network:
    driver: bridge